name: Build & Deploy CSharpSampleCRUDTest.NET APP

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CSharpSampleCRUDTest_image: '${{ secrets.DOCKER_HUB_USERNAME }}/CSharpSampleCRUDTest'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create Docker Image
      run: dotnet publish ./CSharpSampleCRUDTest.API.csproj /t:PublishContainer -r linux-x64
    - name: change image tag
      run: docker tag CSharpSampleCRUDTest ${{ env.CSharpSampleCRUDTest_image }}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Docker Push
      run: docker push ${{ env.CSharpSampleCRUDTest_image }}
    
